### ISSUE TITLE
プロダクトからLoveChainを取り除きRoootを配置する

### ISSUE THREAD

**Issue by fukui-takanori** [drip-pages/drip-official#119]
## 概要
プロダクトのうち、LoveChainをそっ閉じするので、これを取り除く。
代わりにRoootを追加する。

## 手段
差し替え。
画像・ロゴについてはデザイナーさんに依頼中

**Comment by drcm-ogawa-mitsunori** [comment]
### 中くらい

![Rooot-LOGO_middle](https://user-images.githubusercontent.com/11750757/109755250-012a8800-7c29-11eb-9fff-7f49fec81fb5.png)

### 大きい

![Rooot-LOGO_large](https://user-images.githubusercontent.com/11750757/109755255-04257880-7c29-11eb-9629-aeee235b969c.png)

**Comment by drcm-ogawa-mitsunori** [comment]
ニュースも追加したい。
https://gamebiz.jp/?p=289959

**Comment by drcm-ogawa-mitsunori** [comment]
@fukui-takanori 

#132 にてサイト更新まで達成しました。
close 確認お願いします。 🙇

**Comment by fukui-takanori** [comment]
ご対応いただきありがとうございます。
確認しましたので、クローズいたします。
