### ISSUE TITLE
Github Actions を活用してサイト更新を楽にしたい

### ISSUE THREAD

**Issue by drcm-ogawa-mitsunori** [drip-pages/drip-official#136]
# Why

#51 #75 関連。
master へのマージ後に人力が無くてもサイト更新される状態を作りたい、かつ MR が見づらくならないよう成果物を MR に加えない状態を保ちたい。
探したところ Github Actions を活用して Github Pages を更新するやり方があるそうなので、目的が達成されそうか調べ、対応したい。
参考: https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d

**Comment by fukui-takanori** [comment]
https://github.com/fukui-takanori/ogp-tester
OGP表示テストで作成していたgithub-pagesを流用して何度かテストしてみたところ、うまくいったため、こちらでも実施する。

**Comment by fukui-takanori** [comment]
以下のPRによって無事にGitHub Actionsを使ってデプロイに成功した。
https://github.com/drip-pages/drip-official/pull/138

しかし、Custom Domainの欄が空欄になってしまい、
https://drip.drecom.co.jp/
にアクセスすると404が発生した。
<img width="810" alt="スクリーンショット 2021-09-15 16 41 42" src="https://user-images.githubusercontent.com/52432522/133391745-77ff087d-c248-47cc-af37-dc67c92eeda4.png">

次にデプロイする時も同じくなる可能性があるため、対応方法を調査する。
（もしくは初回だから発生したのかも？）

**Comment by fukui-takanori** [comment]
https://zenn.dev/nikaera/articles/hugo-github-actions-for-github-pages
cname を設定でいけそう

**Comment by drcm-ogawa-mitsunori** [comment]
@fukui-takanori 

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname

**Comment by fukui-takanori** [comment]
🙇

**Comment by fukui-takanori** [comment]
@drcm-ogawa-mitsunori 
以下2つの本番更新PRによってGitHub Actionsを活用してサイト更新が可能となりました。
https://github.com/drip-pages/drip-official/pull/138
https://github.com/drip-pages/drip-official/pull/140

途中で問題となっていたCNAME と pp.txtについても解決の確認が取れています。

▼CNAMEが入っていることを確認
https://github.com/drip-pages/drip-official/settings/pages
<img width="466" alt="スクリーンショット 2021-09-15 17 56 59" src="https://user-images.githubusercontent.com/52432522/133403469-dc013df0-fcf9-405a-b103-8525542ac9a8.png">

▼pp.txtが入っていることを確認
https://drip.drecom.co.jp/pp.txt

クローズ確認をお願いいたします。
